#ifndef DLLDEBITORCREDIT_GLOBAL_H
#define DLLDEBITORCREDIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLDEBITORCREDIT_LIBRARY)
#  define DLLDEBITORCREDIT_EXPORT Q_DECL_EXPORT
#else
#  define DLLDEBITORCREDIT_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLDEBITORCREDIT_GLOBAL_H
